### ISSUE TITLE
Don't add the variable type in labels

### ISSUE THREAD

**Issue by yulric** [Big-Life-Lab/cchsflow#127]
**Describe the bug**

Variables which are categorized versions of continuous variables like [pct_time_der_cat10](https://github.com/Big-Life-Lab/cchsflow/blob/master/inst/extdata/variables.csv#L238) and [diet_score_cat3](https://github.com/Big-Life-Lab/cchsflow/blob/master/inst/extdata/variables.csv#L91) have the text `categorical` in their label. When describing variables in a paper, for example in a table, their type is usually included along with the label. This means that the labels and type currently have overlapping information for these variables as seen below,

| Variable | Variable Type | Categories |
|----------|----------------|-------------|
| Categorical diet score | Categorical | Poor diet |
|  | | Fair diet |
|  |  | Adequate diet |

Consider removing the type for a variable from its label.

**To Reproduce**

NA

**Expected behavior**

NA

**Screenshots**

NA 

**Desktop (please complete the following information):**

NA

**Additional context**

NA

**Comment by kittychenn** [comment]
@yulric does it only apply to label or should labelLong also be updated?

**Comment by yulric** [comment]
I'm only using the `label` column for my study, so at least that. Should be fine for `labelLong`. Not sure what others think.

**Comment by kittychenn** [comment]
@yulric label has been updated without categorical in the name
