### ISSUE TITLE
Remove disease name from the categories for disease variables

### ISSUE THREAD

**Issue by yulric** [Big-Life-Lab/cchsflow#128]
**Describe the bug**

Most of the disease variable include the name of the disease in their category labels. For example, [arthritis](https://github.com/Big-Life-Lab/cchsflow/blob/master/inst/extdata/variable_details.csv#L237-L241) and [back problem](https://github.com/Big-Life-Lab/cchsflow/blob/master/inst/extdata/variable_details.csv#L242-L246). This information is redundant since the category for a variable is usually presented within the  context of the original variable. Practically, it makes a paper's table unnecessarily wordy as can be seen below,

| Variable | Type | Categories |
|----------|-------|-------------| 
| Arthritis | Dichotomous | Yes Arthritis/Rheumatism |
| | | No Arthritis/Rheumatism |

Consider renaming the category labels to **Yes** and **No**.

**To Reproduce**

NA

**Expected behavior**

NA

**Screenshots**

NA

**Desktop (please complete the following information):**

NA

**Additional context**

NA

**Comment by kittychenn** [comment]
@yulric for catLabel and catStartLabel only?

**Comment by yulric** [comment]
Definitely `catLabel`. For `catLabelLong`, I think its find?

**Comment by kittychenn** [comment]
@yulric catLabel has been updated without disease name
