### ISSUE TITLE
Low-income cut-off

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/cchsflow#17]
Is it possible to replicate ratio of low-income cut-off (LICO)? Note that CCHS does not include a variable for family size.

**Comment by DougManuel** [comment]
For LICO, we would also need household income as a continuous variable and household size.

**Comment by wyusuf068** [comment]
LICO requires geographic size which is only included in the Master files of CCHS. PUMF files do not contain area-based measures.
