### ISSUE TITLE
Food insecurity

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/cchsflow#19]
Which variable(s) are best used for multiple CCHS cycles?

Check HRUPoRT and studies by Valerie Tarasuk.

**Comment by wyusuf068** [comment]
`food_insecurity_der` is now included as a variable in cchsflow.

See documentation [here](https://github.com/Big-Life-Lab/cchsflow/blob/master/R/food-insecurity.R) for details on how it was derived.
