### ISSUE TITLE
Diet - SDS

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/cchsflow#20]
Add 'simplified diet score' using CCHS 2007 as the reference population for means (normalization).

**Comment by wyusuf068** [comment]
Diet scores requires the use of z-score to generate a standardized score for survey respondents. This goes against cchsflow's current workflow as z-scores are reliant on the data provided. We are working on how to implement a step to generate z-scores during the data transformation and harmonization process, so we will consider adding SDS diet score along with Perez diet score as variables in the future.
