### ISSUE TITLE
Binge drinking

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/cchsflow#26]
Assess whether binge drinking can be added to cchsflow.

**Comment by DougManuel** [comment]
Preliminary review shows challenges with consistent variable. @wyusuf068 can you provide more updates?

**Comment by wyusuf068** [comment]
Binge drinking has been added to cchsflow using binge_drinker_fun() to derive binge drinking based off daily alcohol consumption. See [here](https://big-life-lab.github.io/cchsflow/reference/binge_drinker_fun.html) for more details.
