### ISSUE TITLE
Multiple chronic conditions

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/cchsflow#37]
There are different options. Consider major conditions (mostly lower prevalence) and minor conditions (such as hypertension and obesity that are really risk factors more than chronic diseases).

Reference is Muggah et al.

**Comment by DougManuel** [comment]
Major conditions potentially include: 

1. Heart Disease
2. Active Cancer
3. Stroke
4. Bowel disorder
5. Mood disorder
6. Respiratory Condition
7. Arthritis/Rheumatism
8. Epilepsy

Categories:
0, 1, 2, 3, 4, 5+

**Comment by wyusuf068** [comment]
`multiple_conditions` derived variable has been added to cchsflow. See [here](https://big-life-lab.github.io/cchsflow/reference/multiple_conditions_fun1.html) for documentation.
