### ISSUE TITLE
Social provision scale & social isolation variables

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/cchsflow#48]
What variables are available in the CCHS for social provision & social isolation?

**Comment by heatherorpana** [comment]
Sense of community belonging is core in CCHS: "How would you describe your sense of belonging to your local community? Would you say it is:  very strong? somewhat strong? somewhat weak? very weak?"

Social provisions scale is thematic and optional - scale changed from 10 item to 5 item version in 2019, but this can be back calculated for consistency across years (See Orpana et al. https://doi.org/10.24095/hpcdp.39.12.02 )

Previously MOS Social Support Scale was used.

I'll identify others and list them here.

**Comment by DougManuel** [comment]
@heatherorpana For clarification, are you suggesting the SDS-5 and components? Can you get us going with the names of the variables for one of the surveys? 

CCHS 2007 is the main starting point that we use. Currently in scope for cchsflow is CCHS 2001 to 2013 X.1 (annual component) PUMF.

**Comment by DougManuel** [comment]
Currently included in _cchsflow_ is GEN_10 and the following:

variable | labelLong
-- | --
GEN_01 | Self perceived health
GEN_02A | Satisfaction with life
GEN_02A2 | Satisfaction with life in general
GEN_02B | Self-perceived mental health
GEN_07 | Self perceived life stress
GEN_09 | Self perceived work stress
GEN_10 | Sense of belonging in the community

**Comment by kittychenn** [comment]
@DougManuel @wyusuf068 @heatherorpana The SDS-10 overall scale and its 5 subscales (attachment, guidance, reliable alliance, social integration, reassurance of worth) are derived variables for 2011 and onwards. We could add the 10 questions to _cchsflow_, and derive the SDS-10 and SDS-5 scales.

**Comment by heatherorpana** [comment]
I don't suggest using the subscales, but agree to use either the 5 or 10
item SPS. I believe the 10 item was discontinued recently in favor of the 5
item. Note there is somewhat of a ceiling effect with this scale. Let me
know if you have any more questions.

**Comment by kittychenn** [comment]
@heatherorpana The MOS Social Support Scale is also present in 2000-2010 with 19 support items ([Sherbourne-Stewart-MOS-Scale.pdf](https://github.com/Big-Life-Lab/cchsflow/files/7944248/Sherbourne-Stewart-MOS-Scale.pdf)).  I tried to match the items in SPS-5 with the MOS scale in the table below. Let me know what you think.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Kitty/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Kitty/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



SPS-5   Items | MOS Items
-- | --
3   I have close relationships that provide me with a sense of emotional security   and well-being. | 20 Someone to love and make you feel wanted
4   There is someone I could talk to about important decisions in my life. | 9 Someone to confide in or talk to about yourself or your problems
5   I have relationships where my competence and skill are recognized. | 8 Someone to give you information to help you understand a situation
7   I feel part of a group of people who share my attitudes and beliefs. | 16 Someone to share your most private worries and fears with
10   There are people I can count on in an emergency. | 4 Someone to give you good advice about a crisis



</body>

</html>


![image](https://user-images.githubusercontent.com/74558106/151224462-85f23f44-755f-4aae-acc8-8885476df052.png)

**Comment by heatherorpana** [comment]
I wouldn't suggest selecting items, rather, if we had both measures in the
same data set (i.e. participants completed both measures) we could see how
reliably these two measures relate to one another. We do this type of
crosswalk in the GBD study when countries use different measures for
specific risk factors. I don't recall, however, if the MOS and SPS were
ever collected together.

**Comment by kittychenn** [comment]
@heatherorpana For CCHS 2012 and 2011/2012, both MOS and SPS were collected together. I can add the measures for both MOS and SPS to _cchsflow_.

To generate SPS-5, I would use the 5 SPS measures mentioned in your study. I'm not sure about how to generate SPS-5 from MOS. For now, I'll use the five-item scale only from SPS.
