### ISSUE TITLE
Language variables

### ISSUE THREAD

**Issue by ribatista** [Big-Life-Lab/cchsflow#52]
**Introduction**

We accept requests and PR for new variables. Providing information about your request helps discussion about whether and how to include the variable.

**Is the variable an existing CCHS variable, or a derived variable?**

These are derived variables that already exist in CCHS cycles.

*What is the name of the variable?**
1. SDCAGLNG/SDCGLNG - Language of conversation
2. SDCGLHM - Language spoken at home
3. SDC_5A_1 - Knowledge of official languages:   
4. SDCDFOLS - First official language spoken (FOLS) 

What is the most consistent name for this variable (usually the variable name used from 2007-2014). If this is an derived variable, what is the name of the derived variable?

**Description of variable**

1. Language of conversation: Language the respondent can converse 
2. Language spoken at home:  Language often or regularly spoken at home by the respondent
3. Knowledge of official languages:  Knowledge of the Canadian official languages
4. First official language spoken: Derived variable based on knowledge of official languages, mother tongue, and language spoken at home.

**Is it consistent across CCHS cycles? If not, explain changes between cycles**

The language of conversation is consistent after 2007
Language of conversation: 
  - SDCAGLNG (c 1.1, 2.1), 
  - SDCEGLNG (c 3.1), 
  - SDCGLNG (c 2007-2008, c 2009-2010)

The language spoken at home is consistent across cycles after 2007Language spoken at home: 
  - SDCGLHM (c 2007-2008 and onward)

The Knowledge of official languages and FOLS are consistent across cycles after 2011
Knowledge of official languages:  
   - SDC_5A_1 (c 2011-2012 and onward)

First official language spoken (FOLS): 
    SDCDFOLS (c 2011-2012 and onward)

**Which cycles is this variable found?**

1. Language of conversation (SDCAGLNG/SDCGLNG): c 1.1, c 2.1, c 3.1, c 2007-2008 and c 2009-2010)
2. Language spoken at home (SDCGLHM): c 2007-2008, c 2009-2010, c 2011-2012, and c 2013-2014
3. Knowledge of official languages ( SDC_5A_1):  c 2011-2012, and c 2013-2014
4. First official language spoken (SDCDFOLS ): c 2011-2012, and c 2013-2014

[Lang vars for cchsflow_mar25.xlsx](https://github.com/Big-Life-Lab/cchsflow/files/4381797/Lang.vars.for.cchsflow_mar25.xlsx)

**Comment by wyusuf068** [comment]
Language variables have been added as part of the cchsflow 1.6.0 release. See [here](https://big-life-lab.github.io/cchsflow/news/index.html#cchsflow-160-latest-build) for more details.
