### ISSUE TITLE
New variable request: Occupation

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/cchsflow#54]
Assess how feasible occupation can be added to cchsflow.

**Comment by wyusuf068** [comment]
Occupation is a single variable available in CCHS 2001 and CCHS cycles 2007-2014.

2001 variable has 9 distinct categories, while variables from 2007-2014 have 5 distinct categories that are consistent.

**Comment by yulric** [comment]
The attached document has categories for various occupations groups in CCHS along with Xs to indicate which category was included in a cycle. The column name also includes the name of the variable for that cycle along with the sample size number for the people who answered the question.

[Occupation Harmonization.xlsx](https://github.com/Big-Life-Lab/cchsflow/files/5190885/Occupation.Harmonization.xlsx)

I think we should create a 9 category variable for which for CCHS 2001. We could also create a 5 category variable for the other cycles but the category values are not completely equivalent.

**Comment by DougManuel** [comment]
Here is a paper that harmonized occupation CCHS data from 2001 to 2014. See table 3. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6423929/

Looks like there is code that describes how recoding was performed. 

Table 1 is a nice summary of variables available across CCHS surveys.

**Comment by DougManuel** [comment]
@yulric I agree with your suggestion:
Two variables:
- nine categories for 2001.
- 5 categories for 2001 to 2014 (with NA for 2003 and 2005).

**Comment by DougManuel** [comment]
From https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6423929/, may be helpful to include:
- number of injuries
- Full-time/part-time employment.
