### ISSUE TITLE
New variable request: second hand smoke

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/cchsflow#55]
Assess how feasible it is to add second-hand smoke to cchsflow.

**Comment by wyusuf068** [comment]
Second-hand smoke variables are available in CCHS cycles 2001-2014.

**Variables that are consistent across all cycles**

1. Exposure to 2nd hand smoke in a vehicle.
2. Exposure to 2nd hand smoke in public places.

**Variables that are consistent with minor differences between cycles**

1. Smoking in the home - In CCHS 2001, survey respondents were asked in the past month if they were exposed to 2nd hand smoke in the home. In CCHS cycles 2003-2014, survey respondents were asked if someone in the home smokes.

**Variables not available across all cycles**

1. Exposure to 2nd hand smoke on most days - variable only available in CCHS 2001.
2. Exposure to 2nd hand smoke when visiting friends or relatives - variable only available in CCHS 2001.
