### ISSUE TITLE
New Variable: Symptoms of Depression

### ISSUE THREAD

**Issue by yulric** [Big-Life-Lab/cchsflow#62]
**Is the variable an existing CCHS variable, or a derived variable?**

Its a newly derived variable

**What is the name of the variable?**

There are 2 variables to consider for this PR,
DPSDSF - Depression Scale - Short form score
DPSDPP - Depression Scale - Predicted probability

**Description of variable**

The variable we want to include should indicate whether a person has symtoms of depression or the condition itself. We can use one of the two variables described above.

**Is it consistent across CCHS cycles? If not, explain changes between cycles**

**DPSDSF**: The derivation for this variable does not change a lot between cycles. Its name changes from *DPSADSF* (CCHS2001) to *DPSCDSF* (CCHS2003) to *DPSEDSF* (CCHS2005) to *DPSDSF* from CCHS 2007-2008 to CCHS 2014. 

ADMC_PRX = 1 (CCHS2003) & ADME_PRX = 1 (CCHS2005) & ADM_PRX = 1 (CCHS2007-2008, CCHS2009 - 2010, CCHS2010, CCHS2011 - 2012, CCHS2012, CCHS2013-2014, CCHS2014) was an additional condition for 99 (NS);  
DPSCFOPT = 2 (CCHS2003) & DPSEFOPT = 2 (CCHS2005) & DPSFOPT = 2 (CCHS2007-2008) & DODEP = 2 (CCHS2009-2010, CCHS2010, CCHS2011-2012, CCHS2012, CCHS2013-2014, CCHS2014) was an additional condition for 96 (NA).

**DPSDPP**: The derivation has not changed a lot. Its name changes from *DPSADPP* (CCHS 2001) to *DPSCDPP* (CCHS 2003) to *DPSEDPP* (CCHS 2005) to *DPSDPP* from CCHS 2007-2010 to CCHS 2014. 

CCHS 2005 to CCHS 2014: ADME_PRX = 1 was also coded as NS

**Which cycles is this variable found?**

In all cycles from CCHS 2001 to CCHS 2014

The attached file has harmonization information for all variables found in the CCHS by searching for the term "depress"
[Depression Symtoms Harmonization.xlsx](https://github.com/Big-Life-Lab/cchsflow/files/5151898/Depression.Symtoms.Harmonization.xlsx)

**Comment by DougManuel** [comment]
@yulric the spreadsheet summary is very helpful. Did you notice sample size for any of the variables? I looks like some where optional content.

**Comment by yulric** [comment]
> 
> 
> @yulric the spreadsheet summary is very helpful. Did you notice sample size for any of the variables? I looks like some where optional content.

@DougManuel I didn't note them down but I can add them to the spreadsheet if you want.

**Comment by DougManuel** [comment]
Yes, please. If could add the sample size for the main variables. We'll generally impute if missing for one cycle or not too many provinces. Studies are starting to drop 2001 and 2003. So, those variables from 2005 onward will be worth considering if all provinces are included.

Optional module flag - Depression

Depression Scale - Short Form Score (D)
Depression Scale - Predicted Probability (D)
Number of weeks last felt depressed - for >  2 weeks - (D)
Specific month felt depressed - 2 weeks in a row - (D)
Has a mood disorder
Frequency - distress: felt sad/depressed - past month
Frequency - distress: depressed/nothing cheers - past month

**Comment by yulric** [comment]
@DougManuel The attached file has the sample sizes for all the variables in each survey. The number at the top is the sample size for each survey in total while the numbers at the side of each variable is the total sample size for all categories except "Not Applicable". 

For CCHS2001, theres something weird going on where the numbers are nearly double or more compared to the other surveys. I didn't take a close look but I'll try to see what the issue is.

[Depression Symtoms Harmonization.xlsx](https://github.com/Big-Life-Lab/cchsflow/files/5162202/Depression.Symtoms.Harmonization.xlsx)

**Comment by DougManuel** [comment]
The questions were mandatory for 2001 but not other years. Looks like less than 50% response for most years, except the mandatory inclusion of 'has mood disorder (DISx_10G) from 2005 onward. This is an unusual situation where there may be very good imputation strategy for some variables. 

For example, DISx_10G for 2001 and 2003 could have good imputation if using other depression variables (in addition to usual imputation variables). Similary, the depression scale variables could be imputed using DISx_10G

**Comment by DougManuel** [comment]
I recommend that we bring into cchsflow the variables that I describe above.

**Comment by yulric** [comment]
Do you mean CCC_280 and not DIS_10G? The former is "Has a mood disorder" amd the later is "Frequency - distress, last month"/

**Comment by Jianli1234** [comment]
Depression Scale - Predicted Probability is derived from Depression Scale - Short Form Score; the purported probability of 0.90 corresponds to 5+ symptom score. So we usually use the predicted probability (1 = 0.90+, vs. 0 = other) in our research, not the score. The advantages are that it is binary variable and the purported probability of 0.90+ is consistent with major depressive episode based on DSM criteria. The disadvantage is it is optional in CCHS. Many CCHS participants did not have the data about this variable. 

Number of weeks depressed in the past 12 months has used to measure duration of a depressive episode. Again, the data are only available in those who have the MDE probability data. 

I have seen studies using anti-depressant usage as a proxy for depression. The problems are that it is vulnerable to reporting bias and some anti-depressant use is not related to depression.

**Comment by DougManuel** [comment]
From Ian Colman <icolman@uottawa.ca>:

>As it seems that you’ve already figured out, the depression module (based on the CIDI Short Form for depression) is optional content in most CCHS waves. Also, the CIDI-SF follows a skip pattern, so respondents only get asked the two stem questions: about having two weeks in a row of dysphoric mood or to endorse questions about having two weeks of anhedonia, lasting most of the day, nearly every day. If they say no to both of those items, they don’t get asked the others.
> 
>I’d have a closer look at the distress score. The K6 score should correlate pretty highly with the CIDI depression score (notwithstanding the odd distribution of the CIDI score due to the skip pattern). Stat Can has largely flipped from the CIDI module for depression to the K6, which is widely used in other research. It would be very helpful with imputation. So will questions about the use of antidepressants or whether a physician has ever diagnosed you with a mood disorder, although those introduce a healthcare-seeking element that isn’t randomly distributed.`

**Comment by wyusuf068** [comment]
See #64

**Comment by yulric** [comment]
Updated harmonization file with mood disorder variable for CCHS 2003 added

[Depression.Symtoms.Harmonization.xlsx](https://github.com/Big-Life-Lab/cchsflow/files/5275580/Depression.Symtoms.Harmonization.xlsx)

**Comment by DougManuel** [comment]
Adding an updated spreadsheet with total numbers across cycles for each questions (see cell "V").
[Depression.Symtoms.Harmonization-5.xlsx](https://github.com/Big-Life-Lab/cchsflow/files/5536523/Depression.Symtoms.Harmonization-5.xlsx)

**Comment by DougManuel** [comment]
Key variables: 
Has mood disorder - `CCC_280` = 773688, missing from CCHS 2001.
Depression Scale - Predicted Probabiltiy (D) = 418750, required for CCHS 2001 but optional for other cycles.
Depression Scale - Predicted Probabiltiy (D) `DPSADPP` = 418750

**Comment by DougManuel** [comment]
@bhaqa044 Here is a paper that examines depression in CCHS from 2000 to 2016. https://www150.statcan.gc.ca/n1/pub/82-003-x/2020012/article/00002-eng.htm
