### ISSUE TITLE
Health regions

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/cchsflow#65]
**Introduction**

We accept requests and PR for new variables. Providing information about your request helps discussion about whether and how to include the variable.

**Is the variable an existing CCHS variable, or a derived variable?**

GEODPMF health region - currently exists in all cycles. 

**What is the name of the variable?**

GEODPMF health region for 2013-14. 

**Description of variable**

Geographic variable for health region.

**Is it consistent across CCHS cycles? If not, explain changes between cycles**

Consistency is a major challenge because health regions have changed over time. 

**Which cycles is this variable found?**

A regional variable is available in all cycles. 

**Additional context**

We'll need to find documentation that helps crosswalk over time. However, suggest that we start by bringing 2013-14 into cchsflow.

**Comment by wyusuf068** [comment]
GEODPMF to be added to cchsflow 1.7.1 as per #66

**Comment by DougManuel** [comment]
Documentation that describes geo boundary changes. https://www150.statcan.gc.ca/n1/en/catalogue/82-402-X

This is a starting point but much info archived and not all years include a description of changes that we could use for CCHS. 

Let's discuss at the presentation at the Canadian Public Health Association and Canadian https://www.cpha.ca/public-health-2020-program and Canadian Alliance for Regional Risk Factor Surveillance (CARRFS) http://www.carrfs.ca. These sessions will have public health epidemiologists from local regions from across Canada.

If needed, we can talk with CCHS staff at Statscan.
