### ISSUE TITLE
Installation error: over-long path length

### ISSUE THREAD

**Issue by jboudr** [Big-Life-Lab/cchsflow#7]
Would it be possible to revisit the file naming conventions used in this package? By default, Windows file names (including extensions) are limited 260 characters. The current file names are too long and cause the package installation to fail. This is particularly problematic for users with limited permissions.

There is a [known issue](https://github.com/r-lib/remotes/issues/84) regarding file naming conventions and `install_github()` on Windows platforms.

```r
> devtools::install_github("Big-Life-Lab/cchsflow")
Downloading GitHub repo Big-Life-Lab/cchsflow@master
√  checking for file 'C:\Users\jboudr\AppData\Local\Temp\Rtmps9j4NF\remotes248c4e7e6d63\Big-Life-Lab-cchsflow-281846f/DESCRIPTION' (470ms)
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path length
    ERROR
   copying to build directory failed
Error: Failed to install 'cchsflow' from GitHub:
  System command error, exit status: 1, stdout + stderr:
E> * checking for file 'C:\Users\jboudr\AppData\Local\Temp\Rtmps9j4NF\remotes248c4e7e6d63\Big-Life-Lab-cchsflow-281846f/DESCRIPTION' ... OK
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   over-long path length
E>  ERROR
E> copying to build directory failed
```

```r
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)
```

**Comment by DarkShadeKnigh** [comment]
Thank you for the issue will look into it. Will reply here once a fix is created.

**Comment by DarkShadeKnigh** [comment]
The issue has been fixed and will be deployed to the master branch by the end of the day. Thank you for bringing this issue to our attention we have addressed it by avoiding full CCHS names and instead opting for short year specific names however full CCHS names can be found in [data.R ](https://github.com/Big-Life-Lab/cchsflow/blob/master/R/data.R)
