### ISSUE TITLE
Smoke_simple

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/cchsflow#79]
Add smoke_simple which a variable that makes four smoking categories from the original CCHS smoking derived variable (SMKDSTY).

**Comment by CBjerke** [comment]
I've finished coding this variable/function but have been unable to push my changes through R. (I miss gitKraken!)

**Comment by wyusuf068** [comment]
See https://github.com/Big-Life-Lab/cchsflow/pull/81.
