### ISSUE TITLE
CCHS yearly data

### ISSUE THREAD

**Issue by kittychenn** [Big-Life-Lab/cchsflow#80]
I have been running into some issues using the yearly data files with cchsflow. 

For example, I want to look at the length of time in Canada in the 2001 CCHS file. 
````
library(readr)
cchs2001 <- read_csv(~/cchs2001)
library(cchsflow)
library(dplyr)

# Length of time in Canada 2001 (recoding single variable)
Ctime2001 <- rec_with_table(cchs2001, "SDCGRES", log = TRUE, attach_data_name = TRUE)
View(Ctime2001)
````

After reading the csv file and running the rec_with_table() function, a warning message pops up and the recoded table (Ctime2001) appears in the environment window. 
![image](https://user-images.githubusercontent.com/74558106/99304218-11f0f280-2820-11eb-8435-6a816d9bf5dd.png)

When looking at the survey answers (1, 2, ..., NA(a), NA(b), etc.) for this table, it didn't show the individual answer options but vector option (image below). The results were all NA. 
![image](https://user-images.githubusercontent.com/74558106/99304300-2df49400-2820-11eb-940c-e81e02f41cf8.png)

I didn't run into this issue with the test data, I'm not sure how to correct this (does this have to do with the warning message?).

I also had an issue with running derived variable functions using the yearly data. For example, I want to look at the percentage of time in Canada using 2001 CCHS file. 
````
# %time in Canada 2001 (derived variable)
pct_time2001 <- rec_with_table(cchs2001, c("DHHGAGE_cont","SDCGCBG", "SDCGRES","pct_time_der"),log=TRUE)
````
After running the rec_with_table() function, a warning message pops up and the recoded table doesn't appear in the environment window. 
![image](https://user-images.githubusercontent.com/74558106/99304980-2681ba80-2821-11eb-84f0-6ad8ad4137f7.png)
Again, I didn't run into this issue with the test data, I'm not sure how to correct this (does this have to do with the error and warning message?).

Thank you in advance!

**Comment by wyusuf068** [comment]
I recommend not using the readr method of importing CSV's (`read_csv()`), and to use the base `read.csv()` function to import a full CCHS dataset into RStudio. The reason being is that `read.csv()` brings a CSV file into RStudio as a data.frame, while `read_csv()` brings a CSV file in as a tibble, which can have parsing issues with the package.

Using your example of examining length of time in Canada this is what I get:
```
cchs2001 <- read.csv(~/cchs2001)
library(cchsflow)
library(dplyr)

> Ctime2001 <- rec_with_table(cchs2001, "SDCGRES", log = TRUE, attach_data_name = TRUE)
Loading cchsflow variable_details
Using the passed data variable name as database_name
NOTE for SDCGRES: CCHS 2001 missing don't know (7), refusal (8)
The variable SDCAGRES was recoded into SDCGRES for the database cchs2001 the following recodes were made: 
  value_to From rows_recoded
1        1    1         3708
2        2    2        13175
3    NA::a    6       113063
4    NA::b  7:9          934
```

And the example of percent time in Canada:
```
> pct_time2001 <- rec_with_table(cchs2001, c("DHHGAGE_cont","SDCGCBG", "SDCGRES","pct_time_der"),log=TRUE)
Loading cchsflow variable_details
Using the passed data variable name as database_name
NOTE for DHHGAGE_cont: Not applicable, don't know, refusal, not stated (96-99) were options in CCHS 2003, but had zero responses
The variable DHHAGAGE was recoded into DHHGAGE_cont for the database cchs2001 the following recodes were made: 
   value_to  From rows_recoded
1        13     1         6476
2        17     2        11081
3        22     3         7584
4        27     4         8742
5        32     5        10281
6        37     6        12447
7        42     7        12886
8        47     8        11388
9        52     9        10255
10       57    10         8355
11       62    11         7152
12       67    12         6842
13       72    13         6360
14       77    14         5237
15       85    15         5794
16    NA::a    96            0
17    NA::b 97:99            0
NOTE for SDCGCBG: CCHS 2001 does not have don't know (7) or refusal (8)
The variable SDCAGCBG was recoded into SDCGCBG for the database cchs2001 the following recodes were made: 
  value_to From rows_recoded
1        1    1       112311
2        2    2        17736
3    NA::a    6            0
4    NA::b  7:9          833
NOTE for SDCGRES: CCHS 2001 missing don't know (7), refusal (8)
The variable SDCAGRES was recoded into SDCGRES for the database cchs2001 the following recodes were made: 
  value_to From rows_recoded
1        1    1         3708
2        2    2        13175
3    NA::a    6       113063
4    NA::b  7:9          934
|=================================================================================== |100% ~0 s remaining 
```

Let me know if you're still running into issues.
